Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HotelSys.Models;
using Microsoft.AspNetCore.Http;

namespace HotelSys.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult ListarClientes()
        {
            ClienteRepo cr = new ClienteRepo();
            List<Cliente> lista = cr.Listar();

            return View(lista);
        }

        public IActionResult Cadastrar()
        {
            if(HttpContext.Session.GetInt32("idUsuario") != null)
                return View();
            else
                return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public IActionResult Cadastrar(Cliente cliente)
        {
            ClienteRepo cr = new ClienteRepo();
            cr.Insert(cliente);

            return RedirectToAction("ListarClientes");
        }
    }
}

Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HotelSys.Models;
using Microsoft.AspNetCore.Http;

namespace HotelSys.Controllers
{
    public class SistemaController : Controller
    {
        public IActionResult Historico()
        {
            if(HttpContext.Session.GetInt32("idUsuario") != null)
            {
                HistoricoRepo hr = new HistoricoRepo();
                List<Historico> lista = hr.Listar();

                return View(lista);
            }
            else
                return RedirectToAction("Login", "Home");
            
        }

        public IActionResult Quartos()
        {
            if (HttpContext.Session.GetInt32("idUsuario") != null)
            {
                QuartoRepo qr = new QuartoRepo();
                List<Quarto> lista = new List<Quarto>();
                lista = qr.Listar();

                return View(lista);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public IActionResult VerQuarto(int id)
        {
            if (HttpContext.Session.GetInt32("idUsuario") != null)
            {
                QuartoRepo qr = new QuartoRepo();
                Quarto quarto = qr.BuscarPorId(id);
                return View(quarto);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        public IActionResult CheckIn(int id)
        {
            if (HttpContext.Session.GetInt32("idUsuario") != null)
            {
                QuartoRepo qr = new QuartoRepo();
                Quarto quarto = qr.BuscarPorId(id);

                return View(quarto);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        [HttpPost]
        public IActionResult CheckIn(Quarto quarto)
        {
            if (HttpContext.Session.GetInt32("idUsuario") != null)
            {
                QuartoRepo qr = new QuartoRepo();
                HistoricoRepo hr = new HistoricoRepo();

                quarto.CheckIn = DateTime.Today;

                qr.Editar(quarto);

                Historico historico = new Historico();
                historico.Quarto = quarto.Numero;
                historico.idCliente = quarto.cliente.idCliente;
                historico.Tipo = "CHECKIN";
                historico.Registro = DateTime.Now;
                hr.Insert(historico);

                return RedirectToAction("Quartos");
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        public IActionResult CheckOut(int id)
        {
            if (HttpContext.Session.GetInt32("idUsuario") != null)
            {
                QuartoRepo qr = new QuartoRepo();
                HistoricoRepo hr = new HistoricoRepo();

                Quarto quarto = qr.BuscarPorId(id);

                Historico historico = new Historico();
                historico.Quarto = quarto.Numero;
                historico.idCliente = quarto.cliente.idCliente;
                historico.Tipo = "CHECKOUT";
                historico.Registro = DateTime.Now;
                hr.Insert(historico);

                quarto.CheckIn = null;
                quarto.CheckOut = null;
                quarto.cliente = new Cliente();
                quarto.cliente.idCliente = 0;
                quarto.Status = "VAZIO";

                qr.Editar(quarto);

                return RedirectToAction("Quartos");
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelSys</title>
    <script src="https://kit.fontawesome.com/69ab88855e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HotelSys</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li> *@

                        @if (Context.Session.GetInt32("idUsuario") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sistema"
                                asp-action="Quartos">Quartos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sistema"
                                asp-action="Historico">Histórico</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente"
                                asp-action="ListarClientes">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HotelSys - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>